#!/bin/bash
# make-executable -- Packages RepRapPro Slicer software into a self-sufficient
# directory whence it can be executed

DESTINATION="executable"
FILELIST="lib/*.jar lib/reprap-icon.png lib/reprap.ico \
	lib/reprappro_logo-0.5.png lib/rr-logo-green-url.png \
	lib/reprap-configurations lib/system-dependent \
	lib/reprap lib/reprap32.bat lib/reprap64.bat"

# Clean out old executable directory
[ -d "$DESTINATION" ] && rm -rf "$DESTINATION"
mkdir "$DESTINATION"

# Recompile java files and create reprap.jar
CLASSPATH=$CLASSPATH:lib/swing-layout-1.0.4.jar ant clean jar || exit 1

# Copy files into $DESTINATION directory
for F in $FILELIST
do
  cp -rp $F "$DESTINATION"
done

chmod 755 "$DESTINATION"/reprap
chmod 755 "$DESTINATION"/reprap32.bat
chmod 755 "$DESTINATION"/reprap64.bat

SOFTWARE_NAME="reprappro_slicer"
RELEASE=${1:-`date -u +%Y%m%d`}
RELEASENAME="$SOFTWARE_NAME-$RELEASE"
echo "RepRapPro Slicer $RELEASENAME created."
