#!/bin/bash
# reprap -- runs RepRapPro Java slicer

INST="$(dirname $0)"

# construct classpath
CP="$INST/reprap.jar:$INST/swing-layout-1.0.4.jar:$INST"

# jvm options, set maximum heap size
JVMOPTS="-Xmx1024M"

# main class
MAIN=org.reprap.Main

exec java -cp "$CP" $JVMOPTS $MAIN "$@"
